import { Formatter, Report, ReportItem } from './base.js';

function actionBadge(action: string, suggested?: string): string {
  switch (action) {
    case 'ok': return '🟢 OK';
    case 'update': return '🔵 Update';
    case 'update-major': return '🟡 Major Update';
    case 'replace': return suggested ? `🔴 Replace with **${suggested}**` : '🔴 Replace';
    case 'review': return '🟣 Review';
    default: return action;
  }
}

function levelBadge(level: string): string {
  switch (level) {
    case 'good': return '🟢 good';
    case 'okay': return '🟡 okay';
    case 'risky': return '🔴 risky';
    case 'critical': return '⛔ critical';
    default: return level;
  }
}

function generateDetails(dep: ReportItem): string {
  const parts: string[] = [];

  parts.push(`- **Maintenance**: ${dep.health.maintenance}/100`);
  parts.push(`- **Popularity**: ${dep.health.popularity}/100`);
  parts.push(`- **Compatibility**: ${dep.health.compatibility}/100`);
  parts.push(`- **Security**: ${dep.health.security}/100`);

  if (dep.health.explanations.length > 0) {
    parts.push(`- **Notes**: ${dep.health.explanations.join('; ')}`);
  }

  return parts.join('\n');
}

export const MarkdownFormatter: Formatter = {
  name: 'markdown',

  format(report: Report): string {
    const lines: string[] = [];

    lines.push('# depcheckai Report');
    lines.push('');
    lines.push(`> **Ecosystem**: ${report.ecosystem} | **Total**: ${report.total} dependencies`);
    lines.push('');
    lines.push('## Summary');
    lines.push('');
    lines.push(`| Level | Count |`);
    lines.push(`|-------|-------|`);
    lines.push(`| 🟢 Good | ${report.summary.good} |`);
    lines.push(`| 🟡 Okay | ${report.summary.okay} |`);
    lines.push(`| 🔴 Risky | ${report.summary.risky} |`);
    lines.push(`| ⛔ Critical | ${report.summary.critical} |`);
    lines.push('');
    lines.push('## Dependencies');
    lines.push('');
    lines.push('| Package | Version | Latest | Health | Score | Action |');
    lines.push('|---------|---------|--------|--------|-------|--------|');

    for (const dep of report.dependencies) {
      const healthBadge = levelBadge(dep.health.level);
      const action = actionBadge(dep.recommendation.action, dep.recommendation.suggested);
      lines.push(
        `| ${dep.name} | ${dep.version} | ${dep.latest} | ${healthBadge} | ${dep.health.overall} | ${action} |`
      );
    }

    lines.push('');
    lines.push('## Details');
    lines.push('');

    for (const dep of report.dependencies) {
      if (dep.recommendation.action === 'ok') continue;
      lines.push(`### ${dep.name} ${dep.version}`);
      lines.push('');
      lines.push(generateDetails(dep));
      lines.push('');
      if (dep.recommendation.reason) {
        lines.push(`**Recommendation**: ${dep.recommendation.reason}`);
        lines.push('');
      }
    }

    lines.push('---');
    lines.push('_Generated by [depcheckai](https://github.com/FMATheNomad/depcheck-ai)_');
    lines.push('');

    return lines.join('\n');
  },
};
